--- #YAML:1.0
name:                Ogre
version:             0.35
abstract:            Perl binding for the OGRE C++ graphics library
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Scott Lanning <slanning@cpan.org>
